Nvm, trying again. Apparently nosetests3 sometimes exists.

diff --git a/build/py/script b/build/py/script
--- a/build/py/script
+++ b/build/py/script
@@ -18,4 +18,14 @@ do
   touch ${dir}/__init__.py
 done
 
-nosetests
+if ! which nosetests
+then
+  echo "nosetests" not found
+fi
+
+if ! which nosetests3
+then
+  echo "nosetests3" not found
+fi
+
+nosetests3
