Fix forgetting to rename build to lang within scripts.

diff --git a/lang/go/script b/lang/go/script
--- a/lang/go/script
+++ b/lang/go/script
@@ -1,13 +1,10 @@
 #!/usr/bin/env bash
 
-set -o xtrace
-
-echo "Building Go!"
+set -e # Exit on error
+set -o xtrace # Trace commands
 
 # All go files must be in the src/ subdirectory:
 #  http://golang.org/doc/code.html#Organization
 rsync -a --include='*.go' --exclude='src/' --include='*/' --exclude='*' -v --prune-empty-dirs . src
 
 go test -v ./src/...
-
-exit 0
diff --git a/lang/js/script b/lang/js/script
--- a/lang/js/script
+++ b/lang/js/script
@@ -1,10 +1,7 @@
 #!/usr/bin/env bash
 
-set -o xtrace
+set -e # Exit on error
+set -o xtrace # Trace commands
 
-echo "Building JS"
-
-npm link build/js
+npm link lang/js
 npm test solvents
-
-exit 0
